name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JASYPT_ENCRYPTOR_PASSWORD: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Docker
        run: cd ./src/main/java/com/rocketden/tester/docker && docker-compose up
      - name: Build with Maven
        run: sudo ./mvnw test

#     TODO: move to deploy step once working
      - name: Update deployment on GCP
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls
            cd tester
            sudo git pull
            pm2 kill
            # Kill hanging process on port 8080 
            sudo kill $(sudo netstat -nlp | grep 8080 | sed -e 's/.*LISTEN *//' -e 's#/.*##')
            pm2 start server.sh
            
          host: ${{ secrets.GCP_HOST }}
          user: alan_bi326_gmail_com
          key: ${{ secrets.GCP_PRIVATE_KEY}}
        

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      JASYPT_ENCRYPTOR_PASSWORD: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rocketden-tester"
          heroku_email: "zpchris@seas.upenn.edu"
